// =============================================================================
// LabPage — Channel-level Knowledge Items management
//
// Displays all channel-scoped KI with category chip-row filter, sort,
// manual creation, and edit/view capabilities.
// =============================================================================

import { useState, useMemo, useCallback } from 'react';
import { Plus, ArrowUpDown } from 'lucide-react';
import { useAuth } from '../../core/hooks/useAuth';
import { useChannelStore } from '../../core/stores/channelStore';
import { useChannelKnowledgeItems, useCreateKnowledgeItem, useUpdateKnowledgeItem } from '../../core/hooks/useKnowledgeItems';
import { useKnowledgeStore } from '../../core/stores/knowledgeStore';
import type { KnowledgeItem } from '../../core/types/knowledge';
import { KnowledgeList } from '../../features/Knowledge/components/KnowledgeList';
import { KnowledgeItemModal } from '../../features/Knowledge/modals/KnowledgeItemModal';

export const LabPage: React.FC = () => {
    const { user } = useAuth();
    const { currentChannel } = useChannelStore();
    const userId = user?.uid || '';
    const channelId = currentChannel?.id || '';

    const { items, isLoading } = useChannelKnowledgeItems(userId, channelId);
    const updateMutation = useUpdateKnowledgeItem(userId, channelId);
    const createMutation = useCreateKnowledgeItem(userId, channelId);

    const { selectedCategory, setCategory, sortOrder, setSortOrder } = useKnowledgeStore();

    const [editingItem, setEditingItem] = useState<KnowledgeItem | null>(null);
    const [isCreating, setIsCreating] = useState(false);

    // Extract unique categories from existing items
    const categories = useMemo(() => {
        const cats = new Set(items.map(i => i.category));
        return Array.from(cats).sort();
    }, [items]);

    // Filter + sort items
    const filteredItems = useMemo(() => {
        let result = items;
        if (selectedCategory) {
            result = result.filter(i => i.category === selectedCategory);
        }
        return result.sort((a, b) => {
            const aTime = a.createdAt?.toMillis?.() ?? 0;
            const bTime = b.createdAt?.toMillis?.() ?? 0;
            return sortOrder === 'newest' ? bTime - aTime : aTime - bTime;
        });
    }, [items, selectedCategory, sortOrder]);

    const handleSave = useCallback((updates: { title: string; content: string; summary?: string }) => {
        if (!editingItem) return;
        updateMutation.mutate(
            { itemId: editingItem.id, updates },
            { onSuccess: () => setEditingItem(null) },
        );
    }, [editingItem, updateMutation]);

    const handleCreate = useCallback((data: { title: string; content: string }) => {
        createMutation.mutate(
            { title: data.title, content: data.content, summary: '', category: 'general', scope: 'channel' },
            { onSuccess: () => setIsCreating(false) },
        );
    }, [createMutation]);

    return (
        <div className="p-6 w-full max-w-[1200px] mx-auto">
            {/* Header */}
            <div className="flex items-center justify-between mb-6">
                <div>
                    <h1 className="text-xl font-semibold text-[var(--color-text-primary)]">
                        AI Research Lab
                    </h1>
                    <p className="text-sm text-[var(--color-text-tertiary)] mt-1">
                        Channel-level insights generated by the AI assistant
                    </p>
                </div>
                <button
                    type="button"
                    onClick={() => setIsCreating(true)}
                    className="flex items-center gap-1.5 px-3 py-2 text-sm font-medium rounded-lg bg-[var(--color-accent)] text-white hover:bg-[var(--color-accent-hover)] transition-colors"
                >
                    <Plus size={16} />
                    Add
                </button>
            </div>

            {/* Filter bar: category chips + sort */}
            {categories.length > 0 && (
                <div className="flex items-center gap-3 mb-4 flex-wrap">
                    {/* Category chips */}
                    <div className="flex items-center gap-1.5 flex-wrap">
                        <button
                            type="button"
                            onClick={() => setCategory(null)}
                            className={`px-3 py-1 text-xs font-medium rounded-full transition-colors ${
                                selectedCategory === null
                                    ? 'bg-[var(--color-accent)] text-white'
                                    : 'bg-[var(--color-bg-tertiary)] text-[var(--color-text-secondary)] hover:bg-[var(--color-bg-hover)]'
                            }`}
                        >
                            All
                        </button>
                        {categories.map(cat => (
                            <button
                                key={cat}
                                type="button"
                                onClick={() => setCategory(selectedCategory === cat ? null : cat)}
                                className={`px-3 py-1 text-xs font-medium rounded-full transition-colors ${
                                    selectedCategory === cat
                                        ? 'bg-[var(--color-accent)] text-white'
                                        : 'bg-[var(--color-bg-tertiary)] text-[var(--color-text-secondary)] hover:bg-[var(--color-bg-hover)]'
                                }`}
                            >
                                {cat}
                            </button>
                        ))}
                    </div>

                    {/* Sort toggle */}
                    <button
                        type="button"
                        onClick={() => setSortOrder(sortOrder === 'newest' ? 'oldest' : 'newest')}
                        className="ml-auto flex items-center gap-1 px-2.5 py-1 text-xs text-[var(--color-text-tertiary)] hover:text-[var(--color-text-primary)] hover:bg-[var(--color-bg-tertiary)] rounded-lg transition-colors"
                        title={`Sort: ${sortOrder === 'newest' ? 'Newest first' : 'Oldest first'}`}
                    >
                        <ArrowUpDown size={14} />
                        {sortOrder === 'newest' ? 'Newest' : 'Oldest'}
                    </button>
                </div>
            )}

            {/* Knowledge Items list */}
            <KnowledgeList
                items={filteredItems}
                isLoading={isLoading}
                onEdit={setEditingItem}
                emptyMessage="No channel research yet. Start a chat conversation and ask the AI to analyze your channel to generate insights."
            />

            {/* Edit modal */}
            {editingItem && (
                <KnowledgeItemModal
                    item={editingItem}
                    onSave={handleSave}
                    onClose={() => setEditingItem(null)}
                    isSaving={updateMutation.isPending}
                />
            )}

            {/* Create modal (reuse KnowledgeItemModal with empty item) */}
            {isCreating && (
                <KnowledgeItemModal
                    item={{
                        id: '',
                        title: '',
                        content: '',
                        summary: '',
                        category: 'general',
                        scope: 'channel',
                        source: 'manual',
                        conversationId: '',
                        model: '',
                        toolsUsed: [],
                        createdAt: null as never,
                    }}
                    onSave={handleCreate}
                    onClose={() => setIsCreating(false)}
                    isSaving={createMutation.isPending}
                />
            )}
        </div>
    );
};
